name: CI Angular app through Github Actions
on: push
jobs:
  build:
    env:
      working-directory: ../../vaulteaclient
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        working-directory: ${{env.working-directory}}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup
        working-directory: ${{env.working-directory}}
        run: npm ci

      - name: Test
        working-directory: ${{env.working-directory}}
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
