name: Angular Tests
on: push
jobs:
  build:
    env:
      working-directory: ./vaulteaclient
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup
        run: npm ci
        working-directory: ${{env.working-directory}}

      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        working-directory: ${{env.working-directory}}
