# Generated by Django 3.2.7 on 2021-12-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
