# Generated by Django 3.2.7 on 2022-01-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_folder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parent_folder_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.folder'),
        ),
    ]
