# Generated by Django 3.2.7 on 2022-01-27 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_folder_parent_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='vault_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.vault'),
        ),
    ]
