# Generated by Django 3.2.7 on 2022-02-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220127_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='description',
            new_name='note',
        ),
        migrations.AddField(
            model_name='password',
            name='username',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='password',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
