# Generated by Django 3.2.7 on 2022-02-11 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220202_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='parent_folder_id',
            new_name='folder_id',
        ),
    ]
