# Generated by Django 3.2.7 on 2022-03-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_parent_folder_id_folder_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='password',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
